### PR TITLE
Fix issues with poller

### PR DESCRIPTION
**Pull request by jcockayne**
Hey,
Thanks for merging the last stuff! As you pointed out there were a couple of issues with redundant tests / test failures as well as the fact that I hadn't added the pbxproj to the commit - this is all included in this pull request. Hope it looks okay.
Jon

### CODE REVIEW

**Comment by azawawi** [comment]
Thanks :+1: but I already fixed it in f9a4be8737957c076114baeb78cfffc7081f91d5 and debdef5a938e71bf40c7888641f24f6565ec1783.

Closing pull request.

**Comment by jcockayne** [comment]
Ah okay, thanks - sorry I was too hasty!
Jon

**Comment by azawawi** [comment]
You should be since you are a Swift programmer :+1:

I really appreciate your help. Maybe take a look at https://github.com/azawawi/SwiftyZeroMQ/issues/4.

**Comment by jcockayne** [comment]
Sure, feel free to assign to me and I will take a look.

**Comment by azawawi** [comment]
Have fun, I am working at the moment on #3. Also I noticed a random test failure [here](https://travis-ci.org/azawawi/SwiftyZeroMQ/jobs/173831630#L488).

**Pull request closed without merging**
