### PR TITLE
multipart send/recv

### PR DESCRIPTION
**Pull request by tjvr**
Hiya! Just a couple methods I found useful—I need to work with multipart messages, which seems like it'd be a good addition to the Swifty library.

Let me know if this is useful to you too—no obligation to merge it! :)

Have a nice day,
Tim

### CODE REVIEW

**Comment by azawawi** [comment]
Awesome. Just a couple of comments for it to get merged. Please add a `defer { }` block to `zmq_msg_close` after creation to handle failures and prevent memory leaks.

**Comment by azawawi** [comment]
@tjvr  Any update on this one?

**Comment by tjvr** [comment]
@azawawi Like this? :)

**Comment by azawawi** [comment]
Thanks 👍

**Comment by tjvr** [comment]
Cheers! :)

**Pull request merged**
